DROP TABLE IF EXISTS PETS, CUSTOMERS;

CREATE TABLE PETS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BREED VARCHAR(256)
);

CREATE TABLE CUSTOMERS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256),
    EMAIL VARCHAR(256),
    ANIMAL VARCHAR(256),
    PET_ID BIGINT REFERENCES PETS(ID)
);